package ycy.tmall.domain;

import ycy.tmall.dao.CategoryMapper;
import ycy.tmall.domain.extension.CategoryExtension;
import ycy.tmall.domain.orm.DomainMapper;

public class Category extends CategoryExtension implements DomainMapper<CategoryMapper> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.recommend
     *
     * @mbggenerated
     */
    private Integer recommend;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.name
     *
     * @return the value of category.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.name
     *
     * @param name the value for category.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.recommend
     *
     * @return the value of category.recommend
     *
     * @mbggenerated
     */
    public Integer getRecommend() {
        return recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.recommend
     *
     * @param recommend the value for category.recommend
     *
     * @mbggenerated
     */
    public void setRecommend(Integer recommend) {
        this.recommend = recommend;
    }
}