package ycy.tmall.domain;

import java.util.Date;
import ycy.tmall.dao.ProductImageMapper;
import ycy.tmall.domain.extension.ProductImageExtension;
import ycy.tmall.domain.orm.DomainMapper;

public class ProductImage extends ProductImageExtension implements DomainMapper<ProductImageMapper> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_image.pid
     *
     * @mbggenerated
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_image.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_image.deleteAt
     *
     * @mbggenerated
     */
    private Date deleteat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_image.pid
     *
     * @return the value of product_image.pid
     *
     * @mbggenerated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_image.pid
     *
     * @param pid the value for product_image.pid
     *
     * @mbggenerated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_image.type
     *
     * @return the value of product_image.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_image.type
     *
     * @param type the value for product_image.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_image.deleteAt
     *
     * @return the value of product_image.deleteAt
     *
     * @mbggenerated
     */
    public Date getDeleteat() {
        return deleteat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_image.deleteAt
     *
     * @param deleteat the value for product_image.deleteAt
     *
     * @mbggenerated
     */
    public void setDeleteat(Date deleteat) {
        this.deleteat = deleteat;
    }
}