package ycy.tmall.domain;

import ycy.tmall.dao.PropertyValueMapper;
import ycy.tmall.domain.extension.PropertyValueExtension;
import ycy.tmall.domain.orm.DomainMapper;

public class PropertyValue extends PropertyValueExtension implements DomainMapper<PropertyValueMapper> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property_value.pid
     *
     * @mbggenerated
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property_value.ptid
     *
     * @mbggenerated
     */
    private Integer ptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property_value.value
     *
     * @mbggenerated
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property_value.pid
     *
     * @return the value of property_value.pid
     *
     * @mbggenerated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property_value.pid
     *
     * @param pid the value for property_value.pid
     *
     * @mbggenerated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property_value.ptid
     *
     * @return the value of property_value.ptid
     *
     * @mbggenerated
     */
    public Integer getPtid() {
        return ptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property_value.ptid
     *
     * @param ptid the value for property_value.ptid
     *
     * @mbggenerated
     */
    public void setPtid(Integer ptid) {
        this.ptid = ptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property_value.value
     *
     * @return the value of property_value.value
     *
     * @mbggenerated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property_value.value
     *
     * @param value the value for property_value.value
     *
     * @mbggenerated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }
}